name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: Packages/WebImagePicker
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build package
        run: swift build

      - name: Test package
        run: swift test
